import Dict from "util/objectOps/Dict";

export const CHALLENGE_LIST = {
  'jbc0': 'JBC Challenge 0',
  'jbc1': 'JBC Challenge 1',
  'jbc2': 'JBC Challenge 2',
  'jbc3': 'JBC Challenge 3',
  'jbc4': 'JBC Challenge 4',
  'jbc5': 'JBC Challenge 5',
  'jbc6': 'JBC Challenge 6',
  'jbc7': 'JBC Challenge 7',
  'jbc8': 'JBC Challenge 8',
  'jbc9': 'JBC Challenge 9',
  'jbc10': 'JBC Challenge 10',
  'jbc11': 'JBC Challenge 11',
  'jbc12': 'JBC Challenge 12',
  'jbc14': 'JBC Challenge 14',
  'jbc15': 'JBC Challenge 15',
  'jbc16': 'JBC Challenge 16',
  'jbc17': 'JBC Challenge 17',
  'jbc18': 'JBC Challenge 18',
  'jbc19': 'JBC Challenge 19',
  'jbc20': 'JBC Challenge 20',
  'jbc21': 'JBC Challenge 21',
  'jbc22': 'JBC Challenge 22',
  'jbc23': 'JBC Challenge 23',
  'jbc24': 'JBC Challenge 24',
  'bex1': 'Botball Explorer 1',
  'bex2': 'Botball Explorer 2',
  'bex3': 'Botball Explorer 3',
  'bex4': 'Botball Explorer 4',
  'bex5': 'Botball Explorer 5',
  'bex6': 'Botball Explorer 6',
  'bex7': 'Botball Explorer 7',
  'bex8': 'Botball Explorer 8',
  'bex9': 'Botball Explorer 9',
  'bex10': 'Botball Explorer 10',
  'bex11': 'Botball Explorer 11',
  'bex12': 'Botball Explorer 12',
  'bex13': 'Botball Explorer 13',
  'bex14': 'Botball Explorer 14',
  'bex15': 'Botball Explorer 15',
  'bex16': 'Botball Explorer 16',
  'bex17': 'Botball Explorer 17',
  'bex18': 'Botball Explorer 18'
} as const;


export type ChallengeName = keyof typeof CHALLENGE_LIST;