enum StandardsLocation {
  UnitedStates = 'United States',
  Alabama = 'Alabama',
  Alaska = 'Alaska',
  Arizona = 'Arizona',
  Arkansas = 'Arkansas',
  California = 'California',
  Colorado = 'Colorado',
  Connecticut = 'Connecticut',
  Delaware = 'Delaware',
  Florida = 'Florida',
  Georgia = 'Georgia',
  Hawaii = 'Hawaii',
  Idaho = 'Idaho',
  Illinois = 'Illinois',
  Indiana = 'Indiana',
  Iowa = 'Iowa',
  Kansas = 'Kansas',
  Kentucky = 'Kentucky',
  Louisiana = 'Louisiana',
  Maine = 'Maine',
  Maryland = 'Maryland',
  Massachusetts = 'Massachusetts',
  Michigan = 'Michigan',
  Minnesota = 'Minnesota',
  Mississippi = 'Mississippi',
  Missouri = 'Missouri',
  Montana = 'Montana',
  Nebraska = 'Nebraska',
  Nevada = 'Nevada',
  NewHampshire = 'New Hampshire',
  NewJersey = 'New Jersey',
  NewMexico = 'New Mexico',
  NewYork = 'New York',
  NorthCarolina = 'North Carolina',
  NorthDakota = 'North Dakota',
  Ohio = 'Ohio',
  Oklahoma = 'Oklahoma',
  Oregon = 'Oregon',
  Pennsylvania = 'Pennsylvania',
  RhodeIsland = 'Rhode Island',
  SouthCarolina = 'South Carolina',
  SouthDakota = 'South Dakota',
  Tennessee = 'Tennessee',
  Texas = 'Texas',
  Utah = 'Utah',
  Vermont = 'Vermont',
  Virginia = 'Virginia',
  Washington = 'Washington',
  WestVirginia = 'West Virginia',
  Wisconsin = 'Wisconsin',
  Wyoming = 'Wyoming',
}

namespace StandardsLocation {
  export const UNITED_STATES_TERRITORIES: Set<StandardsLocation> = new Set([
    StandardsLocation.Alabama,
    StandardsLocation.Alaska,
    StandardsLocation.Arizona,
    StandardsLocation.Arkansas,
    StandardsLocation.California,
    StandardsLocation.Colorado,
    StandardsLocation.Connecticut,
    StandardsLocation.Delaware,
    StandardsLocation.Florida,
    StandardsLocation.Georgia,
    StandardsLocation.Hawaii,
    StandardsLocation.Idaho,
    StandardsLocation.Illinois,
    StandardsLocation.Indiana,
    StandardsLocation.Iowa,
    StandardsLocation.Kansas,
    StandardsLocation.Kentucky,
    StandardsLocation.Louisiana,
    StandardsLocation.Maine,
    StandardsLocation.Maryland,
    StandardsLocation.Massachusetts,
    StandardsLocation.Michigan,
    StandardsLocation.Minnesota,
    StandardsLocation.Mississippi,
    StandardsLocation.Missouri,
    StandardsLocation.Montana,
    StandardsLocation.Nebraska,
    StandardsLocation.Nevada,
    StandardsLocation.NewHampshire,
    StandardsLocation.NewJersey,
    StandardsLocation.NewMexico,
    StandardsLocation.NewYork,
    StandardsLocation.NorthCarolina,
    StandardsLocation.NorthDakota,
    StandardsLocation.Ohio,
    StandardsLocation.Oklahoma,
    StandardsLocation.Oregon,
    StandardsLocation.Pennsylvania,
    StandardsLocation.RhodeIsland,
    StandardsLocation.SouthCarolina,
    StandardsLocation.SouthDakota,
    StandardsLocation.Tennessee,
    StandardsLocation.Texas,
    StandardsLocation.Utah,
    StandardsLocation.Vermont,
    StandardsLocation.Virginia,
    StandardsLocation.Washington,
    StandardsLocation.WestVirginia,
    StandardsLocation.Wisconsin,
    StandardsLocation.Wyoming,
  ]);
}

export default StandardsLocation;